spring:
  application:
    name: MyFortune
  thymeleaf:
    cache: false
  app:
    title: MyFortuce
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: 'jdbc:h2:file:~/h2/myFortune'
    username: 'sa'
    password: '' 
    driver-class-name: 'org.h2.Driver'
  ai:
    vertex:
      ai:
        gemini:
          project-id: '구글 프로젝트 ID'
          location: 'asia-northeast3'
          chat: 
            options:
              model: 'gemini-2.5-flash' #default는 2-0-flash -> asis 지역은 지원 X
key:
  aes256: 'AES256 암호화용 키'

